# Generated by Django 5.2.2 on 2025-08-13 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacaoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_prompt_summary', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulacoes_atendimento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simulação de Atendimento',
                'verbose_name_plural': 'Simulações de Atendimento',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='MensagemSimulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('cliente_ia', 'Cliente (IA)'), ('vendedor_usuario', 'Vendedor (Usuário)')], max_length=20, verbose_name='Remetente')),
                ('message_content', models.TextField(verbose_name='Conteúdo da Mensagem')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('simulacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='webapp.simulacaoatendimento')),
            ],
            options={
                'verbose_name': 'Mensagem da Simulação',
                'verbose_name_plural': 'Mensagens da Simulação',
                'ordering': ['timestamp'],
            },
        ),
    ]
