# Generated by Django 5.2.2 on 2025-09-06 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_criativo', models.CharField(max_length=100, unique=True)),
                ('perfil_disc', models.CharField(choices=[('dominante', 'Dominante'), ('influente', 'Influente'), ('estavel', 'Estável'), ('analitico', 'Analítico')], max_length=20)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('codigo_acesso', models.CharField(blank=True, max_length=10, unique=True)),
                ('capacidade_maxima', models.PositiveIntegerField(default=20)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_criadas', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='salas_participando', to=settings.AUTH_USER_MODEL)),
                ('personagens_disponiveis', models.ManyToManyField(related_name='salas', to='webapp.personagem')),
            ],
        ),
    ]
