# Generated by Django 5.2.2 on 2025-09-06 17:56

from django.db import migrations

def popular_personagens(apps, schema_editor):
    Personagem = apps.get_model('webapp', 'Personagem')
    personagens = [
        {
            "nome_criativo": "Ricardo, o Resoluto",
            "perfil_disc": "dominante",
            "descricao": "Focado em resultados e eficiência. Gosta de ação e desafios."
        },
        {
            "nome_criativo": "Beatriz, a Comunicadora",
            "perfil_disc": "influente",
            "descricao": "Entusiasmada por novidades e conexões. É persuasiva e otimista."
        },
        {
            "nome_criativo": "Sérgio, o Seguro",
            "perfil_disc": "estavel",
            "descricao": "Busca confiança, segurança e um ritmo constante. É paciente e leal."
        },
        {
            "nome_criativo": "Clara, a Criteriosa",
            "perfil_disc": "analitico",
            "descricao": "Precisa de dados, fatos e lógica para decidir. É precisa e organizada."
        },
    ]
    for p in personagens:
        Personagem.objects.create(**p)

class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_personagem_sala'),
    ]

    operations = [
        migrations.RunPython(popular_personagens),
    ]
