# Generated by Django 5.2.2 on 2025-09-06 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_popular_personagens'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulacaoatendimento',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simulacoes', to='webapp.sala'),
        ),
    ]
