# Generated by Django 5.2.2 on 2026-03-08 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_simulacaoatendimento_sala'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaSimulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ponte_abordar', models.FloatField(default=0)),
                ('ponte_pesquisar', models.FloatField(default=0)),
                ('ponte_oferecer', models.FloatField(default=0)),
                ('ponte_negociar', models.FloatField(default=0)),
                ('ponte_tomar_iniciativa', models.FloatField(default=0)),
                ('ponte_estender', models.FloatField(default=0)),
                ('spin_total', models.FloatField(default=0)),
                ('cbv_total', models.FloatField(default=0)),
                ('ortografia', models.FloatField(default=1.0)),
                ('nota_ponte', models.FloatField(default=0)),
                ('nota_ea', models.FloatField(default=0)),
                ('nota_total', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('simulacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='webapp.simulacaoatendimento')),
            ],
            options={
                'verbose_name': 'Auditoria de Simulação',
            },
        ),
    ]
