# Generated by Django 5.2.2 on 2026-03-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auditoriasimulacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoriasimulacao',
            name='erros_ortografia',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
