# Generated by Django 5.2.2 on 2026-03-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auditoriasimulacao_erros_ortografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='notas_liberadas',
            field=models.BooleanField(default=False),
        ),
    ]
